title       = "ncbi"
baseURL     = "https://ncbi-cli.tamnd.com/"
description = "A command line for ncbi."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/ncbi-cli"
